spring.application.name=catalyst
server.port=8800

spring.datasource.url=${DB_URL_T}
spring.datasource.username=${DB_USERNAME_T}
spring.datasource.password=${DB_PASSWORD_T}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


openrouter.api.key=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
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
openrouter.model=stepfun/step-3.5-flash:free

app.jwt.secret=r2jr2qqq223r2r2jr2qqq223r23r555rqq66rr3rjr2jr2qq32meshwarcoders00catalyst

app.email-frontend.base-url=http://localhost:5173